# Use the following line to use Mobile Center Analytics and Crashes.

platform :ios, '10.2'

target 'CoreDataSample' do
pod 'MobileCenter'
end

# Use the following lines if you want to specify which service you want to use.
# pod 'MobileCenter/MobileCenterAnalytics'
# pod 'MobileCenter/MobileCenterCrashes'
